version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - Ffloriel
  ignore:
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  - dependency-name: eslint
    versions:
    - 7.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
