packages:
  - "packages/*"
allowBuilds:
  '@parcel/watcher': true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@typescript-eslint/eslint-plugin@8.71.1'
  - '@typescript-eslint/parser@8.71.1'
  - '@typescript-eslint/type-utils@8.71.1'
  - '@typescript-eslint/utils@8.71.1'
